### ISSUE TITLE
Leaves geo nodes don't generate

### ISSUE THREAD

**Issue by ethanporcaro** [ethanporcaro/modular_tree_py311#2]
The leaves won't generate. I think the old file is out of date

**Comment by ethanporcaro** [comment]
Hey all. It'll probably be a bit before I get to this issue. 

If anyone wants to port over the old geo nodes file from the upstream repo to the current Blender version, that'd be awesome. It won't require any coding. I just don't have time to do it right away.

Sorry about that. Happy blendering for now!

**Comment by noblekat** [comment]
I'm so sorry, I have no idea how to do that. Is there any chance you know of a relevant tutorial I could follow, or that you could lay out the general instructions of how to port them over? I realize that may be the same amount of work, but I'm kinda hitting a wall in my search, so I'm hoping it's simple enough to explain quickly.

**Comment by ethanporcaro** [comment]
Hi all. Try the newest release. If you already tried adding leaves before, delete the existing geo nodes modifier, save and close Blender, then open the file again and use the addon as normal. If you are using a fresh blender file, just use the addon as normal.

**Comment by ethanporcaro** [comment]
Fixed with 9ffbb9c53833212e28c36cedf11fafa66ffaf395

**Comment by AnnaG30** [comment]
Hi there!
Unfortunetly when I try last release, blender still don't want to let me activate this add-on. It shows this:

<img width="588" height="86" alt="Image" src="https://github.com/user-attachments/assets/9ab64887-1c4d-4799-a28d-823257a69644" />

**Comment by ethanporcaro** [comment]
Which OS and blender version are you on? @AnnaG30

**Comment by AnnaG30** [comment]
Win 11 and the newest Blender 4.5 with Vulkano - is this is a problem? Should I use 4.4? I thought about is

**Comment by ethanporcaro** [comment]
@AnnaG30 Unfortunately I cannot reproduce the issue. I am on Windows 11 with blender 4.5.1 with Vulkan enabled. (Windows 10 vs 11 shouldn't matter here)

Are you sure you downloaded from modular_tree_windows.zip from https://github.com/ethanporcaro/modular_tree_py311/releases/tag/v5.0.4 ?

**Comment by ethanporcaro** [comment]
@AnnaG30 Since your error is different than the topic of this issue, and I'm unable to reproduce it, please open a new issue if you still need help 

I'm closing this one because I haven't gotten any complaints and it "works for me" 😉
